# Datos de la investigación del 06-oct-2026 (Meta Ad Library vía Cazar).
# Cada fila resume lo verificado por page_id. "dias" = antigüedad del anuncio activo
# más viejo que pudimos VER (la API ordena por creación y corta en 50).

FECHA = "2026-10-06"

def snap(ad_id):
    return f"https://www.facebook.com/ads/library/?id={ad_id}"

# tier: A = cumple filtro duro verificado (>=20 activos y anuncio activo >=20 días)
#       B = >=20 activos, antigüedad >20 d probable pero no vista directo
#       C = >=20 activos, antigüedad 6-19 días (casi)
#       D = exótico con <20 activos (ángulo para modelar, no cumple volumen)
P = [
    dict(n=1, tier="A", producto="100 Fichas de Fallas de Aire Acondicionado (HVAC)",
         pagina="David Alejandro (ES) + Julien Moreau (FR/IT)", page_id="1240543665811323 / 1263645906829394",
         origen="Operador LATAM (cobra en USD) con persona por idioma", idiomas="ES, FR, IT",
         nicho="Técnicos de aire acondicionado", tipo="Pack de fichas PDF de diagnóstico",
         ads=38, dias=37, viejos=">20 (desde 30-ago)", geo=15, div=6, clones=4, funnel=3,
         precio="No visible en el anuncio", compliance="Sin riesgo",
         avatar="Técnicos de refrigeración y A/A de 25-55 años, independientes o en taller",
         necesidad="Diagnosticar fallas rápido sin cambiar repuestos a ciegas (ganar más por visita)",
         pais="Brasil (PT), Argentina, Chile, Paraguay, Uruguay y México norte: arranca el verano y la temporada de A/A",
         links=[snap("1099224979238232"), snap("1711504169945297"), snap("2065088270810895")]),
    dict(n=2, tier="A", producto="Guía de estudio NCLEX (advertorial \"Read This If…\")",
         pagina="Maya Bennett (+ Alexa Paige, mismo copy)", page_id="1119367354591205",
         origen="Canadá / EE. UU.", idiomas="EN",
         nicho="Enfermería: examen de licencia NCLEX", tipo="Guía PDF / método de estudio",
         ads=72, dias=31, viejos="≥27 con >20 días", geo=10, div=3, clones=8, funnel=3,
         precio="No visible (competidor ReMar arranca en US$3,99)", compliance="Sin riesgo",
         avatar="Enfermeras y enfermeros de 22-40 años que rinden el NCLEX, muchos formados fuera de EE. UU.",
         necesidad="Aprobar el NCLEX a la primera (o después de reprobar) sin pagar cursos de US$300+",
         pais="EE. UU. y Canadá (alto poder adquisitivo); Filipinas, India, Nigeria y LATAM como mercado de enfermeros que migran",
         links=[snap("1864727954938373"), snap("1431052808884405"), snap("1074672455171486")]),
    dict(n=3, tier="A", producto="100 Attività Sensoriali per il tuo Bambino (0–5 anni)",
         pagina="Crescere Giocando", page_id="1009883552206401",
         origen="Italia (EUR)", idiomas="IT",
         nicho="Crianza 0-5 años / Montessori", tipo="Ebook de actividades",
         ads=22, dias=110, viejos="~16 con >20 días (desde 18-jun)", geo=5, div=3, clones=4, funnel=3,
         precio="No visible", compliance="Sin riesgo",
         avatar="Madres de 28-40 años con hijos de 0 a 5, que buscan jugar sin pantallas",
         necesidad="Saber qué hacer con el bebé cada día para estimularlo sin comprar juguetes caros",
         pais="España, México, Chile, Colombia y Brasil (PT): poca competencia digital en ES; en el sur llegan las vacaciones de verano",
         links=[snap("1719132472559701"), snap("1998591761017078")]),
    dict(n=4, tier="A", producto="Moldes PDF de ropa infantil (Tudo para Costura)",
         pagina="Tudo para Costura", page_id="105672138115939",
         origen="Brasil (BRL)", idiomas="PT",
         nicho="Costura infantil", tipo="Moldes PDF graduados RN-14 años",
         ads=28, dias=218, viejos="14 con >20 días (2 desde 2-mar)", geo=5, div=10, clones=12, funnel=3,
         precio="No visible (\"Acesso Imediato\")", compliance="Sin riesgo",
         avatar="Costureras de 30-60 años que cosen para sus hijos/nietos o venden ropa infantil",
         necesidad="Tener moldes que calzan bien por talla, sin dibujarlos ni pagar talleres",
         pais="Brasil ya funciona; en ES el formato \"megapack\" está saturado, el molde premium individual no",
         links=[snap("1435024878102955"), snap("2486005578553305"), snap("28951481117820057")]),
    dict(n=5, tier="A", producto="Mapas visuales de farmacología y estudio (Digi Aprende)",
         pagina="Digi Aprende", page_id="308598599011471",
         origen="Perú (PEN)", idiomas="ES",
         nicho="Estudiantes de salud", tipo="Pack de mapas visuales PDF",
         ads=39, dias=64, viejos="3 con >20 días (desde 3-ago)", geo=10, div=6, clones=11, funnel=3,
         precio="No visible (\"+10.000 descargas\")", compliance="Sin riesgo",
         avatar="Estudiantes de enfermería, farmacia y medicina de 18-30 años en LATAM",
         necesidad="Memorizar más de 500 fármacos para el examen sin leer libros enteros",
         pais="Perú, México, Colombia, Ecuador; traducible a PT-BR",
         links=[snap("1797588771686798"), snap("2128277218074283"), snap("1406272384908009")]),
    dict(n=6, tier="A", producto="\"50 [X] em Feltro\" (colecciones de moldes de fieltro)",
         pagina="Universo do Feltro", page_id="1438504236004203",
         origen="Brasil (BRL)", idiomas="PT",
         nicho="Manualidades en fieltro", tipo="Packs de 50 moldes por temporada",
         ads=66, dias=26, viejos="≥6 con >20 días (desde 10-sep)", geo=5, div=10, clones=6, funnel=3,
         precio="No visible", compliance="Sin riesgo",
         avatar="Mujeres de 30-60 años que hacen artesanías para regalar o vender",
         necesidad="Tener moldes listos de cada fecha (Halloween, Navidad, maternidad) para producir y vender",
         pais="España y LATAM en ES ahora mismo con \"50 adornos navideños en fieltro\" (octubre-diciembre)",
         links=[snap("4000385506938006"), snap("1251647313811839"), snap("4706928642871772")]),
    dict(n=7, tier="A", producto="Catálogo de ebooks esotéricos (Hermetismo, Kejawen, cuántica)",
         pagina="Mekanika Kuantum + Kebangkitan Nusantara + Ma'rifat", page_id="663734000161307 / 624114724110800 / 840028969194310",
         origen="Indonesia (IDR), un solo operador con 3 páginas", idiomas="ID",
         nicho="Espiritualidad y manifestación", tipo="Ebooks temáticos sueltos",
         ads=425, dias=24, viejos="≥8 con >20 días (desde 12-sep)", geo=5, div=10, clones=1, funnel=3,
         precio="No visible", compliance="Riesgo medio (manipulación psicológica, promesas de riqueza)",
         avatar="Adultos de 30-55 años interesados en espiritualidad, ley de atracción y misticismo local",
         necesidad="Encontrar sentido, suerte y abundancia con prácticas \"secretas\"",
         pais="Modelo traducible a ES: Argentina, México y Colombia (Kybalion, leyes herméticas, física cuántica)",
         links=[snap("1084199480647428"), snap("2733515670440769")]),
    dict(n=8, tier="A", producto="Workbooks imprimibles: estudio bíblico + regulación del sistema nervioso",
         pagina="Printable WITH Lisa", page_id="106064502120864",
         origen="EE. UU. (USD)", idiomas="EN",
         nicho="Fe + bienestar emocional", tipo="Workbooks PDF + bundle de toda la tienda",
         ads=79, dias=20, viejos="1 con 20 días (16-sep); retargeting activo", geo=10, div=10, clones=8, funnel=5,
         precio="\"90% off today\" (precio ancla tachado)", compliance="Riesgo medio (\"the cure for anxiety\", trauma)",
         avatar="Mujeres cristianas de 30-55 años; madres con hijas adolescentes ansiosas",
         necesidad="Entender la Biblia sin perderse y calmar la ansiedad con herramientas concretas",
         pais="EE. UU.; en ES funciona para México, Colombia y comunidad hispana en EE. UU.",
         links=[snap("1593599118912122"), snap("1654212152972905"), snap("1141296415084131")]),
    dict(n=9, tier="B", producto="Novela dark romance personalizada (vos sos la protagonista)",
         pagina="Soft Sins", page_id="958645787321203",
         origen="Alemania (EUR)", idiomas="DE",
         nicho="Romance / BookTok", tipo="Libro digital personalizado (generado a pedido)",
         ads=94, dias=14, viejos="44 creados antes del 22-sep sin ver", geo=10, div=6, clones=3, funnel=3,
         precio="No visible", compliance="Revisar (contenido adulto: mantener no explícito)",
         avatar="Mujeres de 20-40 años lectoras de dark romance y romantasy",
         necesidad="Vivir una historia hecha a su medida, con su nombre y su tipo de hombre",
         pais="España, México y Argentina: no vimos ningún anunciante en ES",
         links=[snap("2035041457172040"), snap("1115166987715921")]),
    dict(n=10, tier="B", producto="Atlas de Fotobiomodulación (láser y LED), +900 págs",
         pagina="Lumix Prime", page_id="1256187004432854",
         origen="Brasil (BRL), ya entró a ES", idiomas="PT, ES",
         nicho="Profesionales de salud que usan láser", tipo="Atlas PDF de protocolos",
         ads=137, dias=16, viejos="87 creados antes del 20-sep sin ver", geo=10, div=10, clones=1, funnel=3,
         precio="No visible", compliance="Riesgo bajo (no prometer curas)",
         avatar="Fisioterapeutas, odontólogos y esteticistas de 25-50 años con equipo de láser",
         necesidad="Saber qué protocolo y dosis usar en cada caso sin memorizarlos",
         pais="México, Colombia, Chile y España (el operador recién empezó en ES el 1-oct)",
         links=[snap("1087061917452784"), snap("1063778092956847")]),
    dict(n=11, tier="B", producto="Planes de comidas para adelgazar (mujeres 40+ y menopausia)",
         pagina="Źródło Zdrowych Kalorii", page_id="103582445755560",
         origen="Polonia (PLN)", idiomas="PL",
         nicho="Nutrición femenina", tipo="Jadłospis (menú) PDF + recetarios",
         ads=60, dias=6, viejos="~10 más viejos sin ver", geo=5, div=8, clones=1, funnel=5,
         precio="Cupón \"-20% START\" / \"-25%\"", compliance="Riesgo medio (pérdida de peso)",
         avatar="Mujeres de 40-60 años en perimenopausia",
         necesidad="Bajar de peso sin pasar hambre cuando las dietas de antes ya no funcionan",
         pais="España y México (segmento menopausia en crecimiento)",
         links=[snap("1928559158520867"), snap("1828089905174006")]),
    dict(n=12, tier="B", producto="Patrones de crochet (Sleeping Cat Bag, bundles de 50 y 200)",
         pagina="Soreno", page_id="895892586934815",
         origen="EE. UU. (USD)", idiomas="EN",
         nicho="Crochet", tipo="Patrones PDF",
         ads=55, dias=5, viejos="5 sin ver", geo=10, div=10, clones=10, funnel=3,
         precio="No visible", compliance="Sin riesgo",
         avatar="Mujeres de 25-60 que tejen al crochet",
         necesidad="Patrones bonitos y fáciles para tejer hoy mismo",
         pais="EE. UU., Reino Unido; en ES, México y Argentina",
         links=[snap("1430654619217283"), snap("2530438984144350")]),
    dict(n=13, tier="B", producto="Romance personalizado \"What if the heroine had your name?\"",
         pagina="Ember Books", page_id="935155233023535",
         origen="EE. UU. (USD)", idiomas="EN",
         nicho="Romance / romantasy", tipo="Libro personalizado",
         ads=15, dias=1, viejos="Total no verificado", geo=10, div=8, clones=3, funnel=3,
         precio="No visible", compliance="Revisar (contenido adulto)",
         avatar="Mujeres de 20-45 lectoras de romance",
         necesidad="Una historia escrita para ella",
         pais="Valida el mismo modelo que Soft Sins en otro idioma",
         links=[snap("4662940993984124"), snap("2661018487697258")]),
    dict(n=14, tier="C", producto="Mapas visuales técnicos (mecánica industrial, automatización, ing. civil)",
         pagina="Mapas Visuales PRO", page_id="1291088710759821",
         origen="Perú (PEN), ya exporta a Italia", idiomas="ES, IT",
         nicho="Técnicos e ingenieros", tipo="Megapack de mapas PDF",
         ads=23, dias=18, viejos="0 con >20 días (más viejo 18-sep)", geo=15, div=8, clones=11, funnel=3,
         precio="No visible", compliance="Sin riesgo",
         avatar="Estudiantes técnicos y operarios de industria de 18-40 años",
         necesidad="Entender automatización y mecánica sin libros de 600 páginas",
         pais="Brasil en PT (enorme base de técnicos), México y Colombia en ES",
         links=[snap("1972976284106410"), snap("1395207449448848")]),
    dict(n=15, tier="C", producto="Dibujos para que los chicos creen sin pantallas",
         pagina="Jennifer Collins", page_id="1279411231930580",
         origen="EE. UU. (USD)", idiomas="EN",
         nicho="Crianza / tiempo de pantalla", tipo="Pack imprimible",
         ads=52, dias=16, viejos="0 con >20 días", geo=10, div=6, clones=4, funnel=3,
         precio="No visible", compliance="Sin riesgo",
         avatar="Madres y padres de chicos de 3-10 años",
         necesidad="Sacar al chico de la pantalla sin berrinches",
         pais="EE. UU.; en ES para México y España",
         links=[snap("2122663111659451"), snap("2087294078541472")]),
    dict(n=16, tier="C", producto="Inglés en mapas mentales",
         pagina="Inglés en Mapas", page_id="207806239089657",
         origen="LATAM (USD)", idiomas="ES",
         nicho="Idiomas", tipo="Pack de mapas PDF",
         ads=25, dias=13, viejos="0", geo=10, div=3, clones=11, funnel=3,
         precio="No visible (\"+1.491 descargas\")", compliance="Sin riesgo",
         avatar="Adultos hispanohablantes de 20-45 que quieren inglés básico",
         necesidad="Aprender inglés visual, rápido",
         pais="México, Colombia, Perú",
         links=[snap("1102560409327912")]),
    dict(n=17, tier="C", producto="\"La biblia del oficio inteligente\"",
         pagina="Labibliadeloficiointeligente", page_id="1034500779751800",
         origen="LATAM (USD)", idiomas="ES",
         nicho="Oficios", tipo="Ebook (sin detalle en el título)",
         ads=42, dias=10, viejos="0", geo=10, div=3, clones=1, funnel=3,
         precio="No visible", compliance="Sin riesgo",
         avatar="Trabajadores de oficios (no confirmado)", necesidad="No confirmado: el anuncio solo muestra la reseña 4,9/5",
         pais="LATAM", links=[snap("1604983160618285")]),
    dict(n=18, tier="C", producto="Domina la Química desde Cero",
         pagina="Domina la química desde cero", page_id="1220427307811352",
         origen="BRL, en ES", idiomas="ES",
         nicho="Estudiantes", tipo="Mapas / guía PDF",
         ads=50, dias=6, viejos="0 (lanzado fuerte el 5-oct)", geo=10, div=6, clones=11, funnel=3,
         precio="No visible", compliance="Sin riesgo",
         avatar="Estudiantes de secundaria y primer año universitario", necesidad="Aprobar química",
         pais="México, Colombia, Perú", links=[snap("2298569024262947")]),
    dict(n=19, tier="C", producto="1500 Moldes de Costura (megapack)",
         pagina="1500 Moldes de Costura", page_id="841929342339578",
         origen="LATAM (USD)", idiomas="ES",
         nicho="Costura", tipo="Megapack PDF",
         ads=17, dias=6, viejos="0", geo=10, div=3, clones=12, funnel=3,
         precio="Competidor directo: \"+7.500 moldes US$15\"", compliance="Sin riesgo",
         avatar="Costureras hispanas", necesidad="Moldes de todo tipo en un solo pack",
         pais="Mercado ES ya saturado", links=[snap("1722364679062549")]),
    dict(n=20, tier="C", producto="EducaTech \"Descarga Inmediata\" (+1280 Abogados Innovadores)",
         pagina="EducaTech", page_id="696582943532474",
         origen="LATAM (USD)", idiomas="ES",
         nicho="Profesionales / abogados", tipo="Packs descargables",
         ads=17, dias=21, viejos="1 con >20 días", geo=10, div=3, clones=1, funnel=3,
         precio="No visible", compliance="Sin riesgo",
         avatar="Abogados y profesionales jóvenes", necesidad="Plantillas y recursos listos",
         pais="LATAM", links=[snap("1661298955663074")]),
    dict(n=21, tier="D", producto="Moldes de fieltro para emprender (pesebres, Navidad)",
         pagina="Maestra del Fieltro (+ Taller Lau, Lyzandra)", page_id="1127342340456957",
         origen="Colombia (COP)", idiomas="ES",
         nicho="Manualidades", tipo="Moldes PDF",
         ads=8, dias=42, viejos="5 con >20 días", geo=10, div=6, clones=6, funnel=3,
         precio="Competidora Lyzandra: US$9,99", compliance="Sin riesgo",
         avatar="Mujeres que emprenden con manualidades", necesidad="Ingresos extra en Navidad",
         pais="Colombia, México, Perú", links=[snap("802091959655352")]),
    dict(n=22, tier="D", producto="Tarot desde cero / Astrología / 200 gráficos de radiestesia",
         pagina="Alma, cuerpo y mente", page_id="203461239522395",
         origen="Argentina", idiomas="ES",
         nicho="Esoterismo", tipo="Cursos y packs low ticket",
         ads=6, dias=66, viejos="5 con >20 días", geo=5, div=8, clones=4, funnel=5,
         precio="$3.900 / $5.000 / $7.999 ARS", compliance="Riesgo bajo",
         avatar="Mujeres de 30-60 interesadas en tarot y energía", necesidad="Aprender a leer tarot y radiestesia",
         pais="Argentina, Uruguay, México", links=[snap("3070748743257327")]),
    dict(n=23, tier="D", producto="Atlas visual ACLS / PALS (soporte vital)",
         pagina="Katarzyna Lis", page_id="1240229362515282",
         origen="Polonia (cobra en USD)", idiomas="PL",
         nicho="Emergentología / enfermería", tipo="Atlas PDF",
         ads=6, dias=27, viejos="1 con >20 días", geo=5, div=6, clones=1, funnel=3,
         precio="No visible", compliance="Sin riesgo",
         avatar="Enfermeros y paramédicos", necesidad="Memorizar algoritmos de RCP avanzada",
         pais="Traducible a ES para enfermería LATAM", links=[snap("1495713305653263")]),
    dict(n=24, tier="D", producto="Guía práctica de Vastu a ₹99",
         pagina="Pixel Theory", page_id="1057559637450806",
         origen="India (INR)", idiomas="EN/HI",
         nicho="Vastu / feng shui indio", tipo="Ebook",
         ads=8, dias=6, viejos="0", geo=5, div=6, clones=1, funnel=5,
         precio="₹99", compliance="Sin riesgo",
         avatar="Familias indias que compran o reforman casa", necesidad="Ordenar la casa según Vastu",
         pais="India (precio muy bajo)", links=[snap("1127931963533410")]),
    dict(n=25, tier="D", producto="PAE Gen: tu Proceso de Atención de Enfermería en minutos",
         pagina="PAE Gen", page_id="1315806514951028",
         origen="LATAM (USD)", idiomas="ES",
         nicho="Estudiantes de enfermería", tipo="Generador / plantilla",
         ads=13, dias=5, viejos="0", geo=10, div=8, clones=1, funnel=3,
         precio="No visible", compliance="Sin riesgo",
         avatar="Estudiantes de enfermería", necesidad="Armar el PAE sin trasnochar",
         pais="México, Perú, Colombia", links=[snap("1571717877491932")]),
    dict(n=26, tier="D", producto="Biblia Etíope (88 libros) + Enoc y Jubileos en español",
         pagina="Camina con Dios", page_id="1339940095866766",
         origen="LATAM (USD)", idiomas="ES",
         nicho="Fe / apócrifos", tipo="Ebooks",
         ads=3, dias=0, viejos="0", geo=10, div=6, clones=1, funnel=5,
         precio="3x1 por $9.890", compliance="Sin riesgo",
         avatar="Cristianos curiosos de 30-65", necesidad="Leer los libros que \"no están en la Biblia\"",
         pais="Chile, Argentina, México", links=[snap("1073329228654543")]),
    dict(n=27, tier="D", producto="Super Pack de Agendas 2027",
         pagina="Jirafa Creativa", page_id="378035388734229",
         origen="LATAM (USD)", idiomas="ES",
         nicho="Papelería digital", tipo="Plantillas imprimibles",
         ads=6, dias=0, viejos="0", geo=10, div=3, clones=4, funnel=3,
         precio="No visible", compliance="Sin riesgo",
         avatar="Emprendedoras de papelería y docentes", necesidad="Agendas 2027 listas para imprimir y vender",
         pais="Estacional: octubre-enero en todo LATAM", links=[snap("1122671533631333")]),
    dict(n=28, tier="D", producto="128 recetas con productos de Biedronka (súper low cost)",
         pagina="Szama za grosze", page_id="1372417475946509",
         origen="Polonia (PLN)", idiomas="PL",
         nicho="Cocina económica", tipo="Recetario + plan semanal",
         ads=3, dias=5, viejos="0", geo=5, div=6, clones=1, funnel=5,
         precio="49,99 zł", compliance="Sin riesgo",
         avatar="Familias que quieren gastar menos en comida", necesidad="Comer bien con el súper más barato",
         pais="Modelable a ES con Mercadona/Lidl (España), Aldi/Bodega Aurrera (México)", links=[snap("1681978020116027")]),
    dict(n=29, tier="D", producto="Ebooks PDF: Constelaciones familiares, uñas, visas",
         pagina="Coursewe", page_id="108029235218668",
         origen="Turquía (TRY)", idiomas="TR",
         nicho="Mixto", tipo="Ebooks PDF",
         ads=5, dias=0, viejos="0", geo=5, div=8, clones=1, funnel=5,
         precio="289-849 TL", compliance="Sin riesgo",
         avatar="Adultos turcos", necesidad="Aprender un oficio o tema puntual",
         pais="Turquía", links=[snap("1934685594167269")]),
    dict(n=30, tier="D", producto="120 juegos sin pantallas para chicos",
         pagina="Unplugged Brain Games", page_id="1414423405078900",
         origen="Operador BRL vendiendo en EN", idiomas="EN",
         nicho="Crianza", tipo="Pack imprimible",
         ads=8, dias=5, viejos="0", geo=10, div=3, clones=4, funnel=3,
         precio="No visible", compliance="Sin riesgo",
         avatar="Padres de chicos de 4-10", necesidad="Menos pantalla",
         pais="EE. UU.", links=[snap("1847379233298463")]),
]


def puntos_antig(d):
    return 20 if d > 15 else (10 if d >= 10 else (5 if d >= 5 else 3))

def puntos_vol(a):
    return 20 if a > 20 else (10 if a >= 15 else (5 if a >= 8 else 3))

def puntos_clon(c):
    if c > 15:
        return 11
    if c >= 5:
        return 20
    if c >= 2:
        return 15
    return 5

def score(p):
    comp = dict(antig=puntos_antig(p["dias"]), vol=puntos_vol(p["ads"]), geo=p["geo"],
                div=p["div"], clon=puntos_clon(p["clones"]), funnel=p["funnel"])
    return sum(comp.values()), comp

def veredicto(s):
    return ("GANADOR FUERTE" if s >= 80 else "GANADOR" if s >= 60 else "POTENCIAL" if s >= 40 else "DESCARTAR")

for p in P:
    p["score"], p["comp"] = score(p)
    p["veredicto"] = veredicto(p["score"])
    p["saturado"] = p["clones"] > 15
